# Generated by Django 4.2.6 on 2023-11-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='description',
        ),
    ]
