name: Django CI/CD

on:
  push:
    branches:
      - main # или другая ветка, которую вы используете

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_NAME: ${{ secrets.DATABASE_NAME }}
      DB_USER: ${{ secrets.DATABASE_USER }}
      DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DB_HOST: ${{ secrets.DATABASE_HOST }}
      DB_PORT: ${{ secrets.DATABASE_PORT }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and run Docker Compose with DB
      run: |
        docker-compose up -d

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # ваша версия Python

    - name: Create and Activate venv
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Run Django tests
      run: |
        ls
        pip list
        python manage.py test
      working-directory: Django/BlogDjango/

    - name: Deploy to production
      run: |
        python manage.py runserver
      working-directory: Django/BlogDjango/
