name: Django CI/CD

on:
  push:
    branches:
      - main # или другая ветка, которую вы используете

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and run Docker Compose with DB
      run: |
        docker-compose up -d

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # ваша версия Python

    - name: Create and Activate venv
      run: |
        python -m venv venv
        source venv/bin/activate
        pip list
      working-directory: Django/BlogDjango/

    - name: Install poetry
      run: |
        source venv/bin/activate
        pip install poetry
      working-directory: Django/BlogDjango/

    - name: Install dependencies
      run: |
        source venv/bin/activate
        poetry install
      working-directory: Django/BlogDjango/

    - name: Run Django tests
      run: |
        source venv/bin/activate
        python manage.py test
      working-directory: Django/BlogDjango/
